// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT uid,
  token
FROM refresh_tokens
WHERE token = $1
  AND expires_at > now()
`

type GetRefreshTokenRow struct {
	Uid   uuid.UUID
	Token string
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(&i.Uid, &i.Token)
	return i, err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :exec
INSERT INTO refresh_tokens (uid, token, expires_at)
VALUES ($1, $2, $3) ON CONFLICT (uid) DO
UPDATE
SET token = EXCLUDED.token,
  expires_at = EXCLUDED.expires_at
`

type UpsertRefreshTokenParams struct {
	Uid       uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertRefreshToken, arg.Uid, arg.Token, arg.ExpiresAt)
	return err
}
