// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    username,
    nickname,
    password_hash,
    email,
    avatar_url
  )
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	Username     string
	Nickname     string
	PasswordHash string
	Email        string
	AvatarUrl    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Nickname,
		arg.PasswordHash,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const getUserByUid = `-- name: GetUserByUid :one
SELECT uid,
  username,
  role,
  email,
  nickname,
  avatar_url,
  description,
  status,
  created_at
FROM users
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

type GetUserByUidRow struct {
	Uid         uuid.UUID
	Username    string
	Role        UserRole
	Email       string
	Nickname    string
	AvatarUrl   string
	Description string
	Status      UserStatus
	CreatedAt   time.Time
}

func (q *Queries) GetUserByUid(ctx context.Context, uid uuid.UUID) (GetUserByUidRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUid, uid)
	var i GetUserByUidRow
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uid,
  username,
  role,
  email,
  nickname,
  avatar_url,
  description,
  status,
  created_at,
  password_hash
FROM users
WHERE username = $1
  AND status = 'NORMAL'::user_status
`

type GetUserByUsernameRow struct {
	Uid          uuid.UUID
	Username     string
	Role         UserRole
	Email        string
	Nickname     string
	AvatarUrl    string
	Description  string
	Status       UserStatus
	CreatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = COALESCE($2, username),
  email = COALESCE($3, email),
  nickname = COALESCE($4, nickname),
  avatar_url = COALESCE($5, avatar_url),
  updated_at = now()
WHERE uid = $1
  AND status = 'NORMAL'::user_status
`

type UpdateUserParams struct {
	Uid       uuid.UUID
	Username  sql.NullString
	Email     sql.NullString
	Nickname  sql.NullString
	AvatarUrl sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Uid,
		arg.Username,
		arg.Email,
		arg.Nickname,
		arg.AvatarUrl,
	)
	return err
}
