CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- users table
CREATE TYPE user_role AS ENUM ('HOST', 'ADMIN', 'USER');
CREATE TYPE user_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    username text NOT NULL UNIQUE,
    role user_role NOT NULL DEFAULT 'USER',
    email text NOT NULL DEFAULT '',
    nickname text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    avatar_url text NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT '',
    status user_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_user_uid ON users (uid);
CREATE INDEX idx_user_username ON users (username);