-- posts table
CREATE TYPE post_visibility AS ENUM ('PUBLIC', 'PRIVATE');
CREATE TYPE post_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    author uuid NOT NULL,
    text text NOT NULL,
    images text [] NOT NULL DEFAULT ARRAY []::text [],
    attachments text [] NOT NULL DEFAULT ARRAY []::text [],
    comment_count integer NOT NULL DEFAULT 0,
    collection_count integer NOT NULL DEFAULT 0,
    like_count integer NOT NULL DEFAULT 0,
    pinned boolean NOT NULL DEFAULT false,
    visibility post_visibility NOT NULL DEFAULT 'PUBLIC',
    latest_replied_on timestamptz NOT NULL DEFAULT now(),
    ip text NOT NULL DEFAULT '',
    status post_status NOT NULL DEFAULT 'NORMAL',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_posts_author ON posts (author);
CREATE INDEX idx_posts_keyset_normal ON posts (created_at DESC, uid DESC)
WHERE status = 'NORMAL'::post_status;
-- tags table
CREATE TABLE tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);
-- post_tags table
CREATE TABLE post_tags (
    post_id integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id integer NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);
CREATE INDEX idx_post_tags_tag_id ON post_tags (tag_id);
-- post_likes table
CREATE TABLE post_likes (
    post_uid uuid NOT NULL REFERENCES posts(uid) ON DELETE CASCADE,
    user_uid uuid NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (post_uid, user_uid)
);
CREATE INDEX idx_post_likes_user_uid ON post_likes (user_uid);
CREATE INDEX idx_post_likes_post_uid_created_at ON post_likes (post_uid, created_at DESC);
-- post_collections table
CREATE TABLE post_collections (
    post_uid uuid NOT NULL REFERENCES posts(uid) ON DELETE CASCADE,
    user_uid uuid NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (post_uid, user_uid)
);
CREATE INDEX idx_post_collections_user_uid ON post_collections (user_uid);
CREATE INDEX idx_post_collections_post_uid_created_at ON post_collections (post_uid, created_at DESC);