-- post comments table
CREATE TYPE comment_status AS ENUM ('NORMAL', 'ARCHIVED');
CREATE TABLE post_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  post_uid uuid NOT NULL,
  author_uid uuid NOT NULL,
  root_uid uuid NOT NULL,
  parent_uid uuid,
  reply_to_author_uid uuid,
  content text NOT NULL,
  images text [] NOT NULL DEFAULT ARRAY []::text [],
  reply_count integer NOT NULL DEFAULT 0,
  like_count integer NOT NULL DEFAULT 0,
  ip text NOT NULL DEFAULT '',
  status comment_status NOT NULL DEFAULT 'NORMAL',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_post_comments_post_keyset_normal ON post_comments (post_uid, created_at DESC, uid DESC)
WHERE status = 'NORMAL'::comment_status
  AND parent_uid IS NULL;
CREATE INDEX idx_post_comments_root_page_normal ON post_comments (root_uid, created_at ASC, uid ASC)
WHERE status = 'NORMAL'::comment_status
  AND root_uid <> uid;
-- comment_likes table
CREATE TABLE comment_likes (
  comment_uid uuid NOT NULL REFERENCES post_comments(uid) ON DELETE CASCADE,
  user_uid uuid NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (comment_uid, user_uid)
);
CREATE INDEX idx_comment_likes_user_uid ON comment_likes (user_uid);
CREATE INDEX idx_comment_likes_comment_uid_created_at ON comment_likes (comment_uid, created_at DESC);
