// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: comment.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Models
type CommentAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentAuthor) Reset() {
	*x = CommentAuthor{}
	mi := &file_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentAuthor) ProtoMessage() {}

func (x *CommentAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentAuthor.ProtoReflect.Descriptor instead.
func (*CommentAuthor) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentAuthor) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CommentAuthor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommentAuthor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Comment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uid              string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Author           *CommentAuthor         `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PostUid          string                 `protobuf:"bytes,3,opt,name=post_uid,json=postUid,proto3" json:"post_uid,omitempty"`
	RootUid          string                 `protobuf:"bytes,4,opt,name=root_uid,json=rootUid,proto3" json:"root_uid,omitempty"`
	ParentUid        string                 `protobuf:"bytes,5,opt,name=parent_uid,json=parentUid,proto3" json:"parent_uid,omitempty"`
	ReplyToAuthorUid string                 `protobuf:"bytes,6,opt,name=reply_to_author_uid,json=replyToAuthorUid,proto3" json:"reply_to_author_uid,omitempty"`
	Content          string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Images           []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	ReplyCount       int32                  `protobuf:"varint,9,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikeCount        int32                  `protobuf:"varint,12,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Liked            bool                   `protobuf:"varint,13,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Comment) GetAuthor() *CommentAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Comment) GetPostUid() string {
	if x != nil {
		return x.PostUid
	}
	return ""
}

func (x *Comment) GetRootUid() string {
	if x != nil {
		return x.RootUid
	}
	return ""
}

func (x *Comment) GetParentUid() string {
	if x != nil {
		return x.ParentUid
	}
	return ""
}

func (x *Comment) GetReplyToAuthorUid() string {
	if x != nil {
		return x.ReplyToAuthorUid
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Comment) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Comment) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type CreateTopCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUid       string                 `protobuf:"bytes,1,opt,name=post_uid,json=postUid,proto3" json:"post_uid,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopCommentRequest) Reset() {
	*x = CreateTopCommentRequest{}
	mi := &file_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopCommentRequest) ProtoMessage() {}

func (x *CreateTopCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateTopCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopCommentRequest) GetPostUid() string {
	if x != nil {
		return x.PostUid
	}
	return ""
}

func (x *CreateTopCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTopCommentRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateTopCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CommentCount  int32                  `protobuf:"varint,2,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopCommentResponse) Reset() {
	*x = CreateTopCommentResponse{}
	mi := &file_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopCommentResponse) ProtoMessage() {}

func (x *CreateTopCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateTopCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTopCommentResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateTopCommentResponse) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type CreateReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentUid     string                 `protobuf:"bytes,1,opt,name=parent_uid,json=parentUid,proto3" json:"parent_uid,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyRequest) Reset() {
	*x = CreateReplyRequest{}
	mi := &file_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyRequest) ProtoMessage() {}

func (x *CreateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyRequest.ProtoReflect.Descriptor instead.
func (*CreateReplyRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReplyRequest) GetParentUid() string {
	if x != nil {
		return x.ParentUid
	}
	return ""
}

func (x *CreateReplyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,2,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyResponse) Reset() {
	*x = CreateReplyResponse{}
	mi := &file_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResponse) ProtoMessage() {}

func (x *CreateReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResponse.ProtoReflect.Descriptor instead.
func (*CreateReplyResponse) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateReplyResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateReplyResponse) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type ListTopCommentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PostUid         string                 `protobuf:"bytes,1,opt,name=post_uid,json=postUid,proto3" json:"post_uid,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,2,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"` // unix seconds
	CursorId        string                 `protobuf:"bytes,3,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListTopCommentsRequest) Reset() {
	*x = ListTopCommentsRequest{}
	mi := &file_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopCommentsRequest) ProtoMessage() {}

func (x *ListTopCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListTopCommentsRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{6}
}

func (x *ListTopCommentsRequest) GetPostUid() string {
	if x != nil {
		return x.PostUid
	}
	return ""
}

func (x *ListTopCommentsRequest) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListTopCommentsRequest) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

type ListTopCommentsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Comments            []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorId        string                 `protobuf:"bytes,3,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTopCommentsResponse) Reset() {
	*x = ListTopCommentsResponse{}
	mi := &file_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopCommentsResponse) ProtoMessage() {}

func (x *ListTopCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListTopCommentsResponse) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{7}
}

func (x *ListTopCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListTopCommentsResponse) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListTopCommentsResponse) GetNextCursorId() string {
	if x != nil {
		return x.NextCursorId
	}
	return ""
}

type ListRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`    // root comment uid
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 1-based
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesRequest) Reset() {
	*x = ListRepliesRequest{}
	mi := &file_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesRequest) ProtoMessage() {}

func (x *ListRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesRequest.ProtoReflect.Descriptor instead.
func (*ListRepliesRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{8}
}

func (x *ListRepliesRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ListRepliesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepliesResponse) Reset() {
	*x = ListRepliesResponse{}
	mi := &file_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepliesResponse) ProtoMessage() {}

func (x *ListRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepliesResponse.ProtoReflect.Descriptor instead.
func (*ListRepliesResponse) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListRepliesResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListRepliesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRepliesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCommentRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=common.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{11}
}

func (x *LikeCommentRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LikeCommentRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_ADD
}

type LikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResponse) Reset() {
	*x = LikeCommentResponse{}
	mi := &file_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResponse) ProtoMessage() {}

func (x *LikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResponse.ProtoReflect.Descriptor instead.
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{12}
}

func (x *LikeCommentResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_comment_proto protoreflect.FileDescriptor

const file_comment_proto_rawDesc = "" +
	"\n" +
	"\rcomment.proto\x12\acomment\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"k\n" +
	"\rCommentAuthor\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tB\x03\xe0A\x02R\bnickname\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tB\x03\xe0A\x02R\tavatarUrl\"\xcc\x03\n" +
	"\aComment\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x123\n" +
	"\x06author\x18\x02 \x01(\v2\x16.comment.CommentAuthorB\x03\xe0A\x02R\x06author\x12\x1e\n" +
	"\bpost_uid\x18\x03 \x01(\tB\x03\xe0A\x02R\apostUid\x12\x1e\n" +
	"\broot_uid\x18\x04 \x01(\tB\x03\xe0A\x02R\arootUid\x12\x1d\n" +
	"\n" +
	"parent_uid\x18\x05 \x01(\tR\tparentUid\x12-\n" +
	"\x13reply_to_author_uid\x18\x06 \x01(\tR\x10replyToAuthorUid\x12\x1d\n" +
	"\acontent\x18\a \x01(\tB\x03\xe0A\x02R\acontent\x12\x1b\n" +
	"\x06images\x18\b \x03(\tB\x03\xe0A\x02R\x06images\x12$\n" +
	"\vreply_count\x18\t \x01(\x05B\x03\xe0A\x02R\n" +
	"replyCount\x12\"\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03B\x03\xe0A\x02R\tcreatedAt\x12\"\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03B\x03\xe0A\x02R\tupdatedAt\x12\"\n" +
	"\n" +
	"like_count\x18\f \x01(\x05B\x03\xe0A\x02R\tlikeCount\x12\x19\n" +
	"\x05liked\x18\r \x01(\bB\x03\xe0A\x02R\x05liked\"p\n" +
	"\x17CreateTopCommentRequest\x12\x1e\n" +
	"\bpost_uid\x18\x01 \x01(\tB\x03\xe0A\x02R\apostUid\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tB\x03\xe0A\x02R\acontent\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\"[\n" +
	"\x18CreateTopCommentResponse\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12(\n" +
	"\rcomment_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\fcommentCount\"W\n" +
	"\x12CreateReplyRequest\x12\"\n" +
	"\n" +
	"parent_uid\x18\x01 \x01(\tB\x03\xe0A\x02R\tparentUid\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tB\x03\xe0A\x02R\acontent\"R\n" +
	"\x13CreateReplyResponse\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12$\n" +
	"\vreply_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\n" +
	"replyCount\"\x81\x01\n" +
	"\x16ListTopCommentsRequest\x12\x1e\n" +
	"\bpost_uid\x18\x01 \x01(\tB\x03\xe0A\x02R\apostUid\x12*\n" +
	"\x11cursor_created_at\x18\x02 \x01(\x03R\x0fcursorCreatedAt\x12\x1b\n" +
	"\tcursor_id\x18\x03 \x01(\tR\bcursorId\"\xb1\x01\n" +
	"\x17ListTopCommentsResponse\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x10.comment.CommentB\x03\xe0A\x02R\bcomments\x128\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03B\x03\xe0A\x02R\x13nextCursorCreatedAt\x12)\n" +
	"\x0enext_cursor_id\x18\x03 \x01(\tB\x03\xe0A\x02R\fnextCursorId\"?\n" +
	"\x12ListRepliesRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"|\n" +
	"\x13ListRepliesResponse\x121\n" +
	"\bcomments\x18\x01 \x03(\v2\x10.comment.CommentB\x03\xe0A\x02R\bcomments\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05B\x03\xe0A\x02R\x04page\x12\x19\n" +
	"\x05total\x18\x03 \x01(\x05B\x03\xe0A\x02R\x05total\"-\n" +
	"\x14DeleteCommentRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\"Y\n" +
	"\x12LikeCommentRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.common.ToggleActionR\x06action\"0\n" +
	"\x13LikeCommentResponse\x12\x19\n" +
	"\x05count\x18\x01 \x01(\x05B\x03\xe0A\x02R\x05count2\xe1\x05\n" +
	"\x0eCommentService\x12\x85\x01\n" +
	"\x10CreateTopComment\x12 .comment.CreateTopCommentRequest\x1a!.comment.CreateTopCommentResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/v1/posts/{post_uid}/comments\x12z\n" +
	"\vCreateReply\x12\x1b.comment.CreateReplyRequest\x1a\x1c.comment.CreateReplyResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/comments/{parent_uid}/replies\x12\x7f\n" +
	"\x0fListTopComments\x12\x1f.comment.ListTopCommentsRequest\x1a .comment.ListTopCommentsResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/posts/{post_uid}/comments\x12p\n" +
	"\vListReplies\x12\x1b.comment.ListRepliesRequest\x1a\x1c.comment.ListRepliesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/comments/{uid}/replies\x12f\n" +
	"\rDeleteComment\x12\x1d.comment.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/v1/comments/{uid}\x12p\n" +
	"\vLikeComment\x12\x1b.comment.LikeCommentRequest\x1a\x1c.comment.LikeCommentResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/comments/{uid}/likeB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_comment_proto_rawDescOnce sync.Once
	file_comment_proto_rawDescData []byte
)

func file_comment_proto_rawDescGZIP() []byte {
	file_comment_proto_rawDescOnce.Do(func() {
		file_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)))
	})
	return file_comment_proto_rawDescData
}

var file_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_comment_proto_goTypes = []any{
	(*CommentAuthor)(nil),            // 0: comment.CommentAuthor
	(*Comment)(nil),                  // 1: comment.Comment
	(*CreateTopCommentRequest)(nil),  // 2: comment.CreateTopCommentRequest
	(*CreateTopCommentResponse)(nil), // 3: comment.CreateTopCommentResponse
	(*CreateReplyRequest)(nil),       // 4: comment.CreateReplyRequest
	(*CreateReplyResponse)(nil),      // 5: comment.CreateReplyResponse
	(*ListTopCommentsRequest)(nil),   // 6: comment.ListTopCommentsRequest
	(*ListTopCommentsResponse)(nil),  // 7: comment.ListTopCommentsResponse
	(*ListRepliesRequest)(nil),       // 8: comment.ListRepliesRequest
	(*ListRepliesResponse)(nil),      // 9: comment.ListRepliesResponse
	(*DeleteCommentRequest)(nil),     // 10: comment.DeleteCommentRequest
	(*LikeCommentRequest)(nil),       // 11: comment.LikeCommentRequest
	(*LikeCommentResponse)(nil),      // 12: comment.LikeCommentResponse
	(ToggleAction)(0),                // 13: common.ToggleAction
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_comment_proto_depIdxs = []int32{
	0,  // 0: comment.Comment.author:type_name -> comment.CommentAuthor
	1,  // 1: comment.ListTopCommentsResponse.comments:type_name -> comment.Comment
	1,  // 2: comment.ListRepliesResponse.comments:type_name -> comment.Comment
	13, // 3: comment.LikeCommentRequest.action:type_name -> common.ToggleAction
	2,  // 4: comment.CommentService.CreateTopComment:input_type -> comment.CreateTopCommentRequest
	4,  // 5: comment.CommentService.CreateReply:input_type -> comment.CreateReplyRequest
	6,  // 6: comment.CommentService.ListTopComments:input_type -> comment.ListTopCommentsRequest
	8,  // 7: comment.CommentService.ListReplies:input_type -> comment.ListRepliesRequest
	10, // 8: comment.CommentService.DeleteComment:input_type -> comment.DeleteCommentRequest
	11, // 9: comment.CommentService.LikeComment:input_type -> comment.LikeCommentRequest
	3,  // 10: comment.CommentService.CreateTopComment:output_type -> comment.CreateTopCommentResponse
	5,  // 11: comment.CommentService.CreateReply:output_type -> comment.CreateReplyResponse
	7,  // 12: comment.CommentService.ListTopComments:output_type -> comment.ListTopCommentsResponse
	9,  // 13: comment.CommentService.ListReplies:output_type -> comment.ListRepliesResponse
	14, // 14: comment.CommentService.DeleteComment:output_type -> google.protobuf.Empty
	12, // 15: comment.CommentService.LikeComment:output_type -> comment.LikeCommentResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_comment_proto_init() }
func file_comment_proto_init() {
	if File_comment_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_proto_goTypes,
		DependencyIndexes: file_comment_proto_depIdxs,
		MessageInfos:      file_comment_proto_msgTypes,
	}.Build()
	File_comment_proto = out.File
	file_comment_proto_goTypes = nil
	file_comment_proto_depIdxs = nil
}
