// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: follow.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Follow
type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=common.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FollowRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_ADD
}

type FollowResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowingCount int32                  `protobuf:"varint,1,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowersCount int32                  `protobuf:"varint,2,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *FollowResponse) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

// List
type ListMyFollowersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CursorCreatedAt int64                  `protobuf:"varint,1,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"` // unix seconds
	CursorId        string                 `protobuf:"bytes,2,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMyFollowersRequest) Reset() {
	*x = ListMyFollowersRequest{}
	mi := &file_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFollowersRequest) ProtoMessage() {}

func (x *ListMyFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListMyFollowersRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyFollowersRequest) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListMyFollowersRequest) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

type ListMyFollowersResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Users               []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorId        string                 `protobuf:"bytes,3,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListMyFollowersResponse) Reset() {
	*x = ListMyFollowersResponse{}
	mi := &file_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFollowersResponse) ProtoMessage() {}

func (x *ListMyFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFollowersResponse.ProtoReflect.Descriptor instead.
func (*ListMyFollowersResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyFollowersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListMyFollowersResponse) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListMyFollowersResponse) GetNextCursorId() string {
	if x != nil {
		return x.NextCursorId
	}
	return ""
}

type ListMyFollowingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CursorCreatedAt int64                  `protobuf:"varint,1,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"` // unix seconds
	CursorId        string                 `protobuf:"bytes,2,opt,name=cursor_id,json=cursorId,proto3" json:"cursor_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMyFollowingRequest) Reset() {
	*x = ListMyFollowingRequest{}
	mi := &file_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFollowingRequest) ProtoMessage() {}

func (x *ListMyFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListMyFollowingRequest) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyFollowingRequest) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *ListMyFollowingRequest) GetCursorId() string {
	if x != nil {
		return x.CursorId
	}
	return ""
}

type ListMyFollowingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Users               []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,2,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorId        string                 `protobuf:"bytes,3,opt,name=next_cursor_id,json=nextCursorId,proto3" json:"next_cursor_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListMyFollowingResponse) Reset() {
	*x = ListMyFollowingResponse{}
	mi := &file_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFollowingResponse) ProtoMessage() {}

func (x *ListMyFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFollowingResponse.ProtoReflect.Descriptor instead.
func (*ListMyFollowingResponse) Descriptor() ([]byte, []int) {
	return file_follow_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyFollowingResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListMyFollowingResponse) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *ListMyFollowingResponse) GetNextCursorId() string {
	if x != nil {
		return x.NextCursorId
	}
	return ""
}

var File_follow_proto protoreflect.FileDescriptor

const file_follow_proto_rawDesc = "" +
	"\n" +
	"\ffollow.proto\x12\x06follow\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\fcommon.proto\"T\n" +
	"\rFollowRequest\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tB\x03\xe0A\x02R\x03uid\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.common.ToggleActionR\x06action\"l\n" +
	"\x0eFollowResponse\x12,\n" +
	"\x0ffollowing_count\x18\x01 \x01(\x05B\x03\xe0A\x02R\x0efollowingCount\x12,\n" +
	"\x0ffollowers_count\x18\x02 \x01(\x05B\x03\xe0A\x02R\x0efollowersCount\"a\n" +
	"\x16ListMyFollowersRequest\x12*\n" +
	"\x11cursor_created_at\x18\x01 \x01(\x03R\x0fcursorCreatedAt\x12\x1b\n" +
	"\tcursor_id\x18\x02 \x01(\tR\bcursorId\"\xa7\x01\n" +
	"\x17ListMyFollowersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\f.common.UserB\x03\xe0A\x02R\x05users\x128\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03B\x03\xe0A\x02R\x13nextCursorCreatedAt\x12)\n" +
	"\x0enext_cursor_id\x18\x03 \x01(\tB\x03\xe0A\x02R\fnextCursorId\"a\n" +
	"\x16ListMyFollowingRequest\x12*\n" +
	"\x11cursor_created_at\x18\x01 \x01(\x03R\x0fcursorCreatedAt\x12\x1b\n" +
	"\tcursor_id\x18\x02 \x01(\tR\bcursorId\"\xa7\x01\n" +
	"\x17ListMyFollowingResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\f.common.UserB\x03\xe0A\x02R\x05users\x128\n" +
	"\x16next_cursor_created_at\x18\x02 \x01(\x03B\x03\xe0A\x02R\x13nextCursorCreatedAt\x12)\n" +
	"\x0enext_cursor_id\x18\x03 \x01(\tB\x03\xe0A\x02R\fnextCursorId2\xd3\x02\n" +
	"\rFollowService\x12^\n" +
	"\x06Follow\x12\x15.follow.FollowRequest\x1a\x16.follow.FollowResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/users/{uid}/follow\x12p\n" +
	"\x0fListMyFollowers\x12\x1e.follow.ListMyFollowersRequest\x1a\x1f.follow.ListMyFollowersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/me/followers\x12p\n" +
	"\x0fListMyFollowing\x12\x1e.follow.ListMyFollowingRequest\x1a\x1f.follow.ListMyFollowingResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/me/followingB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_follow_proto_rawDescOnce sync.Once
	file_follow_proto_rawDescData []byte
)

func file_follow_proto_rawDescGZIP() []byte {
	file_follow_proto_rawDescOnce.Do(func() {
		file_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)))
	})
	return file_follow_proto_rawDescData
}

var file_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_follow_proto_goTypes = []any{
	(*FollowRequest)(nil),           // 0: follow.FollowRequest
	(*FollowResponse)(nil),          // 1: follow.FollowResponse
	(*ListMyFollowersRequest)(nil),  // 2: follow.ListMyFollowersRequest
	(*ListMyFollowersResponse)(nil), // 3: follow.ListMyFollowersResponse
	(*ListMyFollowingRequest)(nil),  // 4: follow.ListMyFollowingRequest
	(*ListMyFollowingResponse)(nil), // 5: follow.ListMyFollowingResponse
	(ToggleAction)(0),               // 6: common.ToggleAction
	(*User)(nil),                    // 7: common.User
}
var file_follow_proto_depIdxs = []int32{
	6, // 0: follow.FollowRequest.action:type_name -> common.ToggleAction
	7, // 1: follow.ListMyFollowersResponse.users:type_name -> common.User
	7, // 2: follow.ListMyFollowingResponse.users:type_name -> common.User
	0, // 3: follow.FollowService.Follow:input_type -> follow.FollowRequest
	2, // 4: follow.FollowService.ListMyFollowers:input_type -> follow.ListMyFollowersRequest
	4, // 5: follow.FollowService.ListMyFollowing:input_type -> follow.ListMyFollowingRequest
	1, // 6: follow.FollowService.Follow:output_type -> follow.FollowResponse
	3, // 7: follow.FollowService.ListMyFollowers:output_type -> follow.ListMyFollowersResponse
	5, // 8: follow.FollowService.ListMyFollowing:output_type -> follow.ListMyFollowingResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_follow_proto_init() }
func file_follow_proto_init() {
	if File_follow_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follow_proto_rawDesc), len(file_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follow_proto_goTypes,
		DependencyIndexes: file_follow_proto_depIdxs,
		MessageInfos:      file_follow_proto_msgTypes,
	}.Build()
	File_follow_proto = out.File
	file_follow_proto_goTypes = nil
	file_follow_proto_depIdxs = nil
}
