// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: post.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToggleAction int32

const (
	ToggleAction_TOGGLE_ACTION_UNSPECIFIED ToggleAction = 0
	ToggleAction_TOGGLE_ACTION_ADD         ToggleAction = 1
	ToggleAction_TOGGLE_ACTION_REMOVE      ToggleAction = 2
)

// Enum value maps for ToggleAction.
var (
	ToggleAction_name = map[int32]string{
		0: "TOGGLE_ACTION_UNSPECIFIED",
		1: "TOGGLE_ACTION_ADD",
		2: "TOGGLE_ACTION_REMOVE",
	}
	ToggleAction_value = map[string]int32{
		"TOGGLE_ACTION_UNSPECIFIED": 0,
		"TOGGLE_ACTION_ADD":         1,
		"TOGGLE_ACTION_REMOVE":      2,
	}
)

func (x ToggleAction) Enum() *ToggleAction {
	p := new(ToggleAction)
	*p = x
	return p
}

func (x ToggleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToggleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_post_proto_enumTypes[0].Descriptor()
}

func (ToggleAction) Type() protoreflect.EnumType {
	return &file_post_proto_enumTypes[0]
}

func (x ToggleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToggleAction.Descriptor instead.
func (ToggleAction) EnumDescriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

type PostAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAuthor) Reset() {
	*x = PostAuthor{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAuthor) ProtoMessage() {}

func (x *PostAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAuthor.ProtoReflect.Descriptor instead.
func (*PostAuthor) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostAuthor) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PostAuthor) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PostAuthor) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Post struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Author          *PostAuthor            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Images          []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Attachments     []string               `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CommentCount    int64                  `protobuf:"varint,7,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CollectionCount int64                  `protobuf:"varint,8,opt,name=collection_count,json=collectionCount,proto3" json:"collection_count,omitempty"`
	LikeCount       int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Visibility      string                 `protobuf:"bytes,10,opt,name=visibility,proto3" json:"visibility,omitempty"`
	LatestRepliedOn int64                  `protobuf:"varint,11,opt,name=latest_replied_on,json=latestRepliedOn,proto3" json:"latest_replied_on,omitempty"`
	Ip              string                 `protobuf:"bytes,12,opt,name=ip,proto3" json:"ip,omitempty"`
	Pinned          bool                   `protobuf:"varint,13,opt,name=pinned,proto3" json:"pinned,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Post) GetAuthor() *PostAuthor {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Post) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Post) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Post) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetCollectionCount() int64 {
	if x != nil {
		return x.CollectionCount
	}
	return 0
}

func (x *Post) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Post) GetLatestRepliedOn() int64 {
	if x != nil {
		return x.LatestRepliedOn
	}
	return 0
}

func (x *Post) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Post) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Post) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Images        []string               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Attachments   []string               `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Pinned        bool                   `protobuf:"varint,6,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreatePostRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreatePostRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *CreatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreatePostRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreatePostRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Search        string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *ListPostsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPostsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPostsRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ListPostsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListPostsRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListPostsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPostsResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Images        []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Attachments   []string               `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Visibility    *string                `protobuf:"bytes,6,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	Pinned        *bool                  `protobuf:"varint,7,opt,name=pinned,proto3,oneof" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdatePostRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *UpdatePostRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdatePostRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *UpdatePostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdatePostRequest) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *UpdatePostRequest) GetPinned() bool {
	if x != nil && x.Pinned != nil {
		return *x.Pinned
	}
	return false
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=post.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_post_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{11}
}

func (x *LikePostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *LikePostRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_UNSPECIFIED
}

type CollectPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        ToggleAction           `protobuf:"varint,2,opt,name=action,proto3,enum=post.ToggleAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectPostRequest) Reset() {
	*x = CollectPostRequest{}
	mi := &file_post_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectPostRequest) ProtoMessage() {}

func (x *CollectPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectPostRequest.ProtoReflect.Descriptor instead.
func (*CollectPostRequest) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{12}
}

func (x *CollectPostRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CollectPostRequest) GetAction() ToggleAction {
	if x != nil {
		return x.Action
	}
	return ToggleAction_TOGGLE_ACTION_UNSPECIFIED
}

type PostCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCounterResponse) Reset() {
	*x = PostCounterResponse{}
	mi := &file_post_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCounterResponse) ProtoMessage() {}

func (x *PostCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCounterResponse.ProtoReflect.Descriptor instead.
func (*PostCounterResponse) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{13}
}

func (x *PostCounterResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"q\n" +
	"\n" +
	"PostAuthor\x12\x18\n" +
	"\x03uid\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\x02R\x03uid\x12\"\n" +
	"\bnickname\x18\x02 \x01(\tB\x06\xe0A\x03\xe0A\x02R\bnickname\x12%\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tB\x06\xe0A\x03\xe0A\x02R\tavatarUrl\"\xbd\x04\n" +
	"\x04Post\x12\x18\n" +
	"\x03uid\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\x02R\x03uid\x120\n" +
	"\x06author\x18\x02 \x01(\v2\x10.post.PostAuthorB\x06\xe0A\x03\xe0A\x02R\x06author\x12\x1a\n" +
	"\x04text\x18\x03 \x01(\tB\x06\xe0A\x03\xe0A\x02R\x04text\x12\x1e\n" +
	"\x06images\x18\x04 \x03(\tB\x06\xe0A\x03\xe0A\x02R\x06images\x12(\n" +
	"\vattachments\x18\x05 \x03(\tB\x06\xe0A\x03\xe0A\x02R\vattachments\x12\x1a\n" +
	"\x04tags\x18\x06 \x03(\tB\x06\xe0A\x03\xe0A\x02R\x04tags\x12+\n" +
	"\rcomment_count\x18\a \x01(\x03B\x06\xe0A\x03\xe0A\x02R\fcommentCount\x121\n" +
	"\x10collection_count\x18\b \x01(\x03B\x06\xe0A\x03\xe0A\x02R\x0fcollectionCount\x12%\n" +
	"\n" +
	"like_count\x18\t \x01(\x03B\x06\xe0A\x03\xe0A\x02R\tlikeCount\x12&\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\tB\x06\xe0A\x03\xe0A\x02R\n" +
	"visibility\x122\n" +
	"\x11latest_replied_on\x18\v \x01(\x03B\x06\xe0A\x03\xe0A\x02R\x0flatestRepliedOn\x12\x16\n" +
	"\x02ip\x18\f \x01(\tB\x06\xe0A\x03\xe0A\x02R\x02ip\x12\x1e\n" +
	"\x06pinned\x18\r \x01(\bB\x06\xe0A\x03\xe0A\x02R\x06pinned\x12%\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03B\x06\xe0A\x03\xe0A\x02R\tcreatedAt\x12%\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03B\x06\xe0A\x03\xe0A\x02R\tupdatedAt\"\xad\x01\n" +
	"\x11CreatePostRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06images\x18\x02 \x03(\tR\x06images\x12 \n" +
	"\vattachments\x18\x03 \x03(\tR\vattachments\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06pinned\x18\x06 \x01(\bR\x06pinned\"<\n" +
	"\x12CreatePostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostB\x06\xe0A\x03\xe0A\x02R\x04post\"\xb0\x01\n" +
	"\x10ListPostsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search\"\x94\x01\n" +
	"\x11ListPostsResponse\x12(\n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostB\x06\xe0A\x03\xe0A\x02R\x05posts\x12.\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x06\xe0A\x03\xe0A\x02R\rnextPageToken\x12%\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03B\x06\xe0A\x03\xe0A\x02R\ttotalSize\"\"\n" +
	"\x0eGetPostRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"9\n" +
	"\x0fGetPostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostB\x06\xe0A\x03\xe0A\x02R\x04post\"\xf1\x01\n" +
	"\x11UpdatePostRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x17\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\x12 \n" +
	"\vattachments\x18\x04 \x03(\tR\vattachments\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12#\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tH\x01R\n" +
	"visibility\x88\x01\x01\x12\x1b\n" +
	"\x06pinned\x18\a \x01(\bH\x02R\x06pinned\x88\x01\x01B\a\n" +
	"\x05_textB\r\n" +
	"\v_visibilityB\t\n" +
	"\a_pinned\"<\n" +
	"\x12UpdatePostResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostB\x06\xe0A\x03\xe0A\x02R\x04post\"%\n" +
	"\x11DeletePostRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"O\n" +
	"\x0fLikePostRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.post.ToggleActionR\x06action\"R\n" +
	"\x12CollectPostRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.post.ToggleActionR\x06action\"=\n" +
	"\x13PostCounterResponse\x12&\n" +
	"\x04post\x18\x01 \x01(\v2\n" +
	".post.PostB\x06\xe0A\x03\xe0A\x02R\x04post*^\n" +
	"\fToggleAction\x12\x1d\n" +
	"\x19TOGGLE_ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TOGGLE_ACTION_ADD\x10\x01\x12\x18\n" +
	"\x14TOGGLE_ACTION_REMOVE\x10\x022\xb8\a\n" +
	"\vPostService\x12Y\n" +
	"\n" +
	"CreatePost\x12\x17.post.CreatePostRequest\x1a\x18.post.CreatePostResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/posts\x12S\n" +
	"\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/posts\x12X\n" +
	"\vListMyPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/me/posts\x12d\n" +
	"\x11ListMyCollections\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/me/collections\x12S\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/posts/{uid}\x12X\n" +
	"\tGetMyPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/me/posts/{uid}\x12_\n" +
	"\n" +
	"UpdatePost\x12\x17.post.UpdatePostRequest\x1a\x18.post.UpdatePostResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/api/v1/posts/{uid}\x12Z\n" +
	"\n" +
	"DeletePost\x12\x17.post.DeletePostRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/posts/{uid}\x12a\n" +
	"\bLikePost\x12\x15.post.LikePostRequest\x1a\x19.post.PostCounterResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/posts/{uid}/like\x12j\n" +
	"\vCollectPost\x12\x18.post.CollectPostRequest\x1a\x19.post.PostCounterResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/posts/{uid}/collectB\x0fZ\raeibi/api;apib\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_post_proto_goTypes = []any{
	(ToggleAction)(0),           // 0: post.ToggleAction
	(*PostAuthor)(nil),          // 1: post.PostAuthor
	(*Post)(nil),                // 2: post.Post
	(*CreatePostRequest)(nil),   // 3: post.CreatePostRequest
	(*CreatePostResponse)(nil),  // 4: post.CreatePostResponse
	(*ListPostsRequest)(nil),    // 5: post.ListPostsRequest
	(*ListPostsResponse)(nil),   // 6: post.ListPostsResponse
	(*GetPostRequest)(nil),      // 7: post.GetPostRequest
	(*GetPostResponse)(nil),     // 8: post.GetPostResponse
	(*UpdatePostRequest)(nil),   // 9: post.UpdatePostRequest
	(*UpdatePostResponse)(nil),  // 10: post.UpdatePostResponse
	(*DeletePostRequest)(nil),   // 11: post.DeletePostRequest
	(*LikePostRequest)(nil),     // 12: post.LikePostRequest
	(*CollectPostRequest)(nil),  // 13: post.CollectPostRequest
	(*PostCounterResponse)(nil), // 14: post.PostCounterResponse
	(*emptypb.Empty)(nil),       // 15: google.protobuf.Empty
}
var file_post_proto_depIdxs = []int32{
	1,  // 0: post.Post.author:type_name -> post.PostAuthor
	2,  // 1: post.CreatePostResponse.post:type_name -> post.Post
	2,  // 2: post.ListPostsResponse.posts:type_name -> post.Post
	2,  // 3: post.GetPostResponse.post:type_name -> post.Post
	2,  // 4: post.UpdatePostResponse.post:type_name -> post.Post
	0,  // 5: post.LikePostRequest.action:type_name -> post.ToggleAction
	0,  // 6: post.CollectPostRequest.action:type_name -> post.ToggleAction
	2,  // 7: post.PostCounterResponse.post:type_name -> post.Post
	3,  // 8: post.PostService.CreatePost:input_type -> post.CreatePostRequest
	5,  // 9: post.PostService.ListPosts:input_type -> post.ListPostsRequest
	5,  // 10: post.PostService.ListMyPosts:input_type -> post.ListPostsRequest
	5,  // 11: post.PostService.ListMyCollections:input_type -> post.ListPostsRequest
	7,  // 12: post.PostService.GetPost:input_type -> post.GetPostRequest
	7,  // 13: post.PostService.GetMyPost:input_type -> post.GetPostRequest
	9,  // 14: post.PostService.UpdatePost:input_type -> post.UpdatePostRequest
	11, // 15: post.PostService.DeletePost:input_type -> post.DeletePostRequest
	12, // 16: post.PostService.LikePost:input_type -> post.LikePostRequest
	13, // 17: post.PostService.CollectPost:input_type -> post.CollectPostRequest
	4,  // 18: post.PostService.CreatePost:output_type -> post.CreatePostResponse
	6,  // 19: post.PostService.ListPosts:output_type -> post.ListPostsResponse
	6,  // 20: post.PostService.ListMyPosts:output_type -> post.ListPostsResponse
	6,  // 21: post.PostService.ListMyCollections:output_type -> post.ListPostsResponse
	8,  // 22: post.PostService.GetPost:output_type -> post.GetPostResponse
	8,  // 23: post.PostService.GetMyPost:output_type -> post.GetPostResponse
	10, // 24: post.PostService.UpdatePost:output_type -> post.UpdatePostResponse
	15, // 25: post.PostService.DeletePost:output_type -> google.protobuf.Empty
	14, // 26: post.PostService.LikePost:output_type -> post.PostCounterResponse
	14, // 27: post.PostService.CollectPost:output_type -> post.PostCounterResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	file_post_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		EnumInfos:         file_post_proto_enumTypes,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
